baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'DokHospital'
theme = 'ananke'

[menu]
  [[menu.main]]
    name = "Accueil"
    url  = "/"
    weight = 1
  [[menu.main]]
    name = "Services"
    url  = "/services/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 3
  [[menu.main]]
    name = "Rendez-vous"
    url  = "/rendezvous/"
    weight = 4

